export const GET_PERSONS_BEGIN = 'GET_PERSONS_BEGIN';
export const GET_PERSONS_SUCCES = 'GET_PERSONS_SUCCES'; 
export const GET_PERSONS_FAILURE = 'GET_PERSONS_FAILURE'; 

export const ADD_PERSON_BEGIN = 'ADD_PERSON_BEGIN'; 
export const ADD_PERSON_SUCCES = 'ADD_PERSON_SUCCES'; 
export const ADD_PERSON_FAILURE = 'ADD_PERSON_FAILURE'; 

export const EDIT_PERSON_BEGIN = 'EDIT_PERSON_BEGIN'; 
export const EDIT_PERSON_SUCCES = 'EDIT_PERSON_SUCCES'; 
export const EDIT_PERSON_FAILURE = 'EDIT_PERSON_FAILURE';

export const DELETE_PERSON_BEGIN = 'DELETE_PERSON_BEGIN'; 
export const DELETE_PERSON_SUCCES = 'DELETE_PERSON_SUCCES'; 
export const DELETE_PERSON_FAILURE = 'DELETE_PERSON_FAILURE';